### ISSUE TITLE
consumes more  bandwidth

### ISSUE THREAD

**Issue by sunxiang520** [webp-sh/webp_server_go#65]
1. when use remote backend services,Server consumes more  bandwidth.Although webp is not dynamically generated for each request,but every request will visit the remote backend picture address.
2. It is recommended to judge whether the webp exists first, and there is no need to request the original picture if it exists, instead of requesting the original picture first, find the webp file according to etag.

**Comment by BennyThink** [comment]
Upon each request, we're using head method to get response headers. We need to do it in the first place because we don't know if the image has been changed.

HEAD method is lightweight, because it only contains http headers. 209B in this example
![image](https://user-images.githubusercontent.com/14024832/101280655-47787280-3805-11eb-9bf9-0020f44b1d3a.png)


For your recommendation, there's a paradox:
> instead of requesting the original picture first, find the webp file according to etag.
we need to know etag, then we can find webp image, and in order to find etag we need to request to remote.


And think of one edge case:
1. we already have one cache webp image
2. remote side has update the image for one same URL.
3. we would then return old webp which is not update-to-date.

**Comment by sunxiang520** [comment]
Although the head method does not return content, frequent establishment of http requests is also a resource consumption. Due to the very low frequency of image changes with the same name, it is recommended to add the cache time configuration (optional parameter) to the configuration file. During the cache time, if  the webp has been generated, there is no need to request the source image address.

**Comment by BennyThink** [comment]
Your `cache time` is a fixed value, which is unstable - by saying unstable I mean how could you make sure that the time you set will always return the correct image? It may be true on most cases, but I'm not wiling to take the chance.

And further more, let's track back to local mode
```go
STAT, err := os.Stat(RawImagePath)

ModifiedTime := STAT.ModTime().Unix()
// webpFilename: abc.jpg.png -> abc.jpg.png.1582558990.webp
WebpFilename := fmt.Sprintf("%s.%d.webp", ImgFilename, ModifiedTime)
```
We have a few lines of code to get the modification time of one image, to help us keep track of whether our webp was outdated.

On remote mode, we take advantages of `etag` and that makes the behavior consistent - and this is as stable as `ModTime()`.

Possibly we make take advantages of standard http cache headers like `Cache-Control: max-age=31536000` or `Last-Modified`. But again, `etag` is one kind of cache validation mechanism and we're using it.


ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching
